name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
          submodules: true
          lfs: false

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_HILL_08B898100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          build_timeout_in_minutes: 30 # Build time out - 从默认的15分钟更改为30分钟
          ###### End of Repository/Build Configurations ######
